### ISSUE TITLE
How to use the openai api service deployed by VLLM to use outlines

### ISSUE THREAD

**Issue by deku0818** [outlines-dev/outlines#1044]
I have a qwen model that runs using the vllm openai api service,
Use models.openai in outlines
But I made a mistake
![image](https://github.com/user-attachments/assets/55e64a65-bf95-4c43-9fe9-3c9c70e18a0d)
![image](https://github.com/user-attachments/assets/382c5ae0-34a3-45b7-a139-5028ca6e54dd)
I specified parameters, but the same error occurred

**Comment by remiconnesson** [comment]
Your issue seems to be unrelated to outlines, but to the model you chose, you might need to specify the tokenizer and not only the model slug.

---

## First you need to launch vLLM with the model you want to serve, so you can either:

A. launch vLLM using outlines: https://outlines-dev.github.io/outlines/reference/serve/vllm/
B. launch vLLM directly:  https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html

## then to use outlines you make requests by specifying what constraint you want

If you chose option A, just read the doc here : https://outlines-dev.github.io/outlines/reference/serve/vllm/
if you chose option B, you need to pass the json schema by using the `extra_body` argument of the OpenAI client as shown here https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters

**Comment by deku0818** [comment]
I finally understand now, thanks a lot!

**Comment by deku0818** [comment]
> Your issue seems to be unrelated to outlines, but to the model you chose, you might need to specify the tokenizer and not only the model slug.
> 
> ## First you need to launch vLLM with the model you want to serve, so you can either:
> A. launch vLLM using outlines: https://outlines-dev.github.io/outlines/reference/serve/vllm/ B. launch vLLM directly: https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
> 
> ## then to use outlines you make requests by specifying what constraint you want
> If you chose option A, just read the doc here : https://outlines-dev.github.io/outlines/reference/serve/vllm/ if you chose option B, you need to pass the json schema by using the `extra_body` argument of the OpenAI client as shown here https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters

thank you! I successfully used openai  to pass extra_body structured output, So how do I use outlines 'sdk?
