### ISSUE TITLE
Add speculative decoding

### ISSUE THREAD

**Issue by SamDuffield** [outlines-dev/outlines#276]
I'm keen on adding [speculative decoding](https://arxiv.org/abs/2211.17192) to outlines.

Is this something that is being worked on? Otherwise I would be happy to submit a PR but I'd need some advice on the API.

I think the following would be the most desirable so that it works with an arbitrary continuation (e.g. regex)
```python
import outlines.text as text

continuation = text.generate.continuation(model)
speculative_continuation = text.speculative_decode(continuation, draft_model)
output = speculative_continuation(prompt)
```

But I wouldn't be sure how to implement this since we'd likely want to modify the `__call__` method of the `continuation` instance.

**Comment by brandonwillard** [comment]
Yes, I believe this is a feature worth adding.

There are some design questions that need to be answered first.  As you implied, a functional/compositional approach would be nice&mdash;one that allows easy mixing and matching of various logit manipulations (e.g. guided/constrained generation) and sampling approaches.

Feel free to open a draft PR that adds the functionality to a custom `Sequence` subclass.  The next-token sampling is performed in `Sequence.step`, so that's a good starting point.

**Comment by SamDuffield** [comment]
Problem is `Sequence.step` generates a single token whereas speculative decoding generates a batch of sequential tokens and then rejects some of them. I don’t see a nice way of implementing this atm without overwriting `__call__` 😿

**Comment by brandonwillard** [comment]
> Problem is `Sequence.step` generates a single token whereas speculative decoding generates a batch of sequential tokens and then rejects some of them. I don’t see a nice way of implementing this atm without overwriting `__call__` 😿

You can override `Sequence.__call__` to get something running; there's no problem with that.
