### ISSUE TITLE
Support for `gpt-3.5-turbo-instruct`

### ISSUE THREAD

**Issue by tranhoangnguyen03** [outlines-dev/outlines#290]
Please add support for `gpt-3.5-turbo-instruct`

**Comment by amir-in-a-cynch** [comment]
@rlouf is this actually completed?

It looks like only gpt-3.5-turbo and gpt-4 are supported here: https://github.com/outlines-dev/outlines/blob/main/outlines/models/openai.py#L107

My suggestion is that instead of hard coding these, just make a best effort and let the error be thrown if the user specifies an invalid model. It'll be easier to keep to update.

**Comment by rlouf** [comment]
Yeah I think you're right
