### ISSUE TITLE
Support for structured information extraction

### ISSUE THREAD

**Issue by horiacristescu** [outlines-dev/outlines#508]
### Presentation of the new feature

When doing information extraction into structured form, we need two things
- ensuring correct JSON formatting
- restricting the model to copying the values

### Where does it fit in Outlines?

There is already support for JSON, but open ended I.E. requires a dynamic schema dependent on the input.

Then we also need to ensure the values of the fields are properly copied. So the model should only be allowed to generate spans that actually exist in the input.

### Are you willing to open a PR?

Just asking

**Comment by lapp0** [comment]
I recommend writing a dynamic regex for each request based on the documents contents. I optimized RegexFSM specifically because the complex unique-per-document regex used were expensive to compile https://github.com/outlines-dev/outlines/pull/507

I think it makes sense to do this on the client side.

**Comment by rlouf** [comment]
Or dynamic JSON schema for this particular use case

**Comment by lapp0** [comment]
Sure, but he's constraining the strings within the schema to match specific spans, so defining a dynamic `"pattern"` makes sense IMO.
